//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Association.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class Rs_Acc_Transaction
    {
        public int Rs_Acc_Transaction_ID { get; set; }
        public System.DateTime RS_Acc_Transaction_Date { get; set; }
        public int RS_Acc_Trans_TypeOfType_ID { get; set; }
        public int Rs_Acc_Transaction_Value { get; set; }
        public string Rs_Acc_Transaction_Check_No { get; set; }
        public Nullable<int> Rs_Acc_Transaction_Member_ID { get; set; }
        public string Rs_Acc_Transaction_Notes { get; set; }
        public string Rs_Acc_Transaction_Image { get; set; }
    
        public virtual RS_Acc_Trans_TypeOfType RS_Acc_Trans_TypeOfType { get; set; }
        public virtual Tbl_Member_Registration Tbl_Member_Registration { get; set; }
    }
}
