//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Association.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class RS_Memb_Transaction
    {
        public int Transaction_ID { get; set; }
        public Nullable<int> Memb_ID { get; set; }
        public Nullable<System.DateTime> TransDate { get; set; }
        public Nullable<int> Distion_No { get; set; }
        public Nullable<int> MembStatus_ID { get; set; }
        public Nullable<int> Reason_ID { get; set; }
        public Nullable<System.DateTime> Status_Date_From { get; set; }
        public Nullable<System.DateTime> Status_Date_To { get; set; }
        public string Status_Note { get; set; }
        public string Trans_Image { get; set; }
    
        public virtual Tbl_Member_Registration Tbl_Member_Registration { get; set; }
        public virtual Tbl_MembStatus Tbl_MembStatus { get; set; }
        public virtual Tbl_Reason_Type Tbl_Reason_Type { get; set; }
    }
}
