//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Association.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_Relation
    {
        public int Relation_ID { get; set; }
        public string Relation_Name { get; set; }
        public int Mem_ID { get; set; }
        public System.DateTime Relation_Birthdate { get; set; }
        public int Gender_ID { get; set; }
        public int kinship_ID { get; set; }
        public string Relation_Image { get; set; }
    
        public virtual Tbl_Gender_Type Tbl_Gender_Type { get; set; }
        public virtual Tbl_kinshipType Tbl_kinshipType { get; set; }
        public virtual Tbl_Member_Registration Tbl_Member_Registration { get; set; }
    }
}
