//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Association.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_Account
    {
        public Tbl_Account()
        {
            this.RS_Acc_Trans_TypeOfType = new HashSet<RS_Acc_Trans_TypeOfType>();
        }
    
        public int Account_ID { get; set; }
        public string Account_Name { get; set; }
    
        public virtual ICollection<RS_Acc_Trans_TypeOfType> RS_Acc_Trans_TypeOfType { get; set; }
    }
}
