//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Association.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_Trining_Process_History_Type
    {
        public Tbl_Trining_Process_History_Type()
        {
            this.Tbl_Trining_Process_History = new HashSet<Tbl_Trining_Process_History>();
        }
    
        public int Tr_Proc_History_Type_ID { get; set; }
        public string Tr_Proc_History_Type_Name { get; set; }
    
        public virtual ICollection<Tbl_Trining_Process_History> Tbl_Trining_Process_History { get; set; }
    }
}
