//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Association.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_Training_Place
    {
        public Tbl_Training_Place()
        {
            this.RS_Traning_Process = new HashSet<RS_Traning_Process>();
        }
    
        public int Training_Place_ID { get; set; }
        public string Training_Place_Name { get; set; }
    
        public virtual ICollection<RS_Traning_Process> RS_Traning_Process { get; set; }
    }
}
