//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Association.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_SysModules
    {
        public TBL_SysModules()
        {
            this.TBL_SysUsers = new HashSet<TBL_SysUsers>();
        }
    
        public int Mod_ID { get; set; }
        public string Module_Name { get; set; }
        public string Module_English_Name { get; set; }
    
        public virtual ICollection<TBL_SysUsers> TBL_SysUsers { get; set; }
    }
}
