//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Association.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_Trining_Process_History
    {
        public int Tr_Proc_History_ID { get; set; }
        public Nullable<int> Tr_Proc_ID { get; set; }
        public Nullable<int> Tr_Proc_History_Type_ID { get; set; }
        public Nullable<int> Memb_EmpID { get; set; }
    
        public virtual RS_Traning_Process RS_Traning_Process { get; set; }
        public virtual Tbl_Trining_Process_History_Type Tbl_Trining_Process_History_Type { get; set; }
    }
}
