//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Association.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_Appraisail_Rate
    {
        public Tbl_Appraisail_Rate()
        {
            this.Tbl_Old_Appraisal = new HashSet<Tbl_Old_Appraisal>();
        }
    
        public int Rate_ID { get; set; }
        public string Rate_Name { get; set; }
    
        public virtual ICollection<Tbl_Old_Appraisal> Tbl_Old_Appraisal { get; set; }
    }
}
