//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Association.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_Old_Appraisal
    {
        public int Appraisal_ID { get; set; }
        public Nullable<int> Memb_ID { get; set; }
        public Nullable<int> Appraisal_Degree { get; set; }
        public Nullable<int> Appraisal_Rate_ID { get; set; }
        public string Appraisal_Year { get; set; }
        public string Appraisal_Image { get; set; }
    
        public virtual Tbl_Appraisail_Rate Tbl_Appraisail_Rate { get; set; }
        public virtual Tbl_Member_Registration Tbl_Member_Registration { get; set; }
    }
}
