//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Association.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_Exception
    {
        public int Excep_ID { get; set; }
        public string Excep_ErrorNumber { get; set; }
        public string Excep_ErrorCode { get; set; }
        public string Excep_Type { get; set; }
        public string Excep_Message { get; set; }
        public Nullable<System.DateTime> Excep_DateTime { get; set; }
        public string EntityMess { get; set; }
    }
}
