//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Association.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_Member_Registration
    {
        public Tbl_Member_Registration()
        {
            this.Rs_Acc_Transaction = new HashSet<Rs_Acc_Transaction>();
            this.RS_Memb_Transaction = new HashSet<RS_Memb_Transaction>();
            this.Tbl_Illegal_Earning = new HashSet<Tbl_Illegal_Earning>();
            this.Tbl_Insurance_Subscripe = new HashSet<Tbl_Insurance_Subscripe>();
            this.Tbl_Member_Insurance = new HashSet<Tbl_Member_Insurance>();
            this.Tbl_Old_Appraisal = new HashSet<Tbl_Old_Appraisal>();
            this.Tbl_Relation = new HashSet<Tbl_Relation>();
            this.Tbl_Subscribes = new HashSet<Tbl_Subscribes>();
        }
    
        public int Memb_ID { get; set; }
        public string National_ID { get; set; }
        public System.DateTime Memb_SysDate { get; set; }
        public Nullable<System.DateTime> Memb_Date { get; set; }
        public string Memb_EmpID { get; set; }
        public string Memb_Name { get; set; }
        public System.DateTime Memb_Birthdate { get; set; }
        public int Memb_Social_ID { get; set; }
        public Nullable<int> Memb_Children_Number { get; set; }
        public string Memb_Image { get; set; }
        public int Memb_Gender_ID { get; set; }
        public string Address { get; set; }
        public string Job { get; set; }
        public string HomePhone { get; set; }
        public string WorkPhone { get; set; }
        public string Mobil { get; set; }
        public string NationalID_Home { get; set; }
        public string BirthHome { get; set; }
        public string Insurance_Number { get; set; }
        public string Folder_Number { get; set; }
        public Nullable<System.DateTime> Emp_Appointment_Date { get; set; }
        public Nullable<int> Sect_ID { get; set; }
        public Nullable<int> Cent_Dept_ID { get; set; }
        public Nullable<int> Pub_Dept_ID { get; set; }
        public Nullable<int> Dept_ID { get; set; }
        public Nullable<int> Edu_Qualification_ID { get; set; }
        public Nullable<int> Work_Degree_ID { get; set; }
        public Nullable<int> Military_Serv_ID { get; set; }
        public Nullable<int> Job_Title_ID { get; set; }
        public Nullable<int> Qualitative_ID { get; set; }
        public Nullable<int> Functional_ID { get; set; }
        public string Email { get; set; }
    
        public virtual ICollection<Rs_Acc_Transaction> Rs_Acc_Transaction { get; set; }
        public virtual ICollection<RS_Memb_Transaction> RS_Memb_Transaction { get; set; }
        public virtual Tbl_Education_Qualification Tbl_Education_Qualification { get; set; }
        public virtual Tbl_Funational_Group Tbl_Funational_Group { get; set; }
        public virtual Tbl_Gender_Type Tbl_Gender_Type { get; set; }
        public virtual ICollection<Tbl_Illegal_Earning> Tbl_Illegal_Earning { get; set; }
        public virtual ICollection<Tbl_Insurance_Subscripe> Tbl_Insurance_Subscripe { get; set; }
        public virtual Tbl_Jobs_Titles Tbl_Jobs_Titles { get; set; }
        public virtual ICollection<Tbl_Member_Insurance> Tbl_Member_Insurance { get; set; }
        public virtual Tbl_Qualitative_Group Tbl_Qualitative_Group { get; set; }
        public virtual Tbl_Military_Service Tbl_Military_Service { get; set; }
        public virtual Tbl_Social Tbl_Social { get; set; }
        public virtual Tbl_Work_Degree Tbl_Work_Degree { get; set; }
        public virtual ICollection<Tbl_Old_Appraisal> Tbl_Old_Appraisal { get; set; }
        public virtual ICollection<Tbl_Relation> Tbl_Relation { get; set; }
        public virtual ICollection<Tbl_Subscribes> Tbl_Subscribes { get; set; }
    }
}
