//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Association.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_IPS
    {
        public int IPS_ID { get; set; }
        public Nullable<int> IPS_Usr_ID { get; set; }
        public string IPS_Usr_IP { get; set; }
    
        public virtual TBL_SysUsers TBL_SysUsers { get; set; }
    }
}
