//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Association.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_Illegal_Earning
    {
        public int Illegal_ID { get; set; }
        public Nullable<int> Memb_ID { get; set; }
        public Nullable<System.DateTime> Illegal_Date { get; set; }
        public string Illegal_Note { get; set; }
        public string Illegal_Image { get; set; }
    
        public virtual Tbl_Member_Registration Tbl_Member_Registration { get; set; }
    }
}
