//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Association.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_Insurance_Subscripe
    {
        public int Insur_ID { get; set; }
        public System.DateTime Insur_Sub_Date { get; set; }
        public Nullable<int> Mem_ID { get; set; }
    
        public virtual Tbl_Member_Registration Tbl_Member_Registration { get; set; }
    }
}
