//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Association.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_Audit_Login
    {
        public int Audit_ID { get; set; }
        public string Audit_IP { get; set; }
        public Nullable<System.DateTime> Audit_DateTime { get; set; }
        public string Audit_UserName { get; set; }
        public string Audit_Password { get; set; }
        public Nullable<bool> Audit_Status { get; set; }
    }
}
