//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Association.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_Insurance_Type
    {
        public Tbl_Insurance_Type()
        {
            this.Tbl_Member_Insurance = new HashSet<Tbl_Member_Insurance>();
        }
    
        public int Insurance_ID { get; set; }
        public string Insurance_Type_Name { get; set; }
    
        public virtual ICollection<Tbl_Member_Insurance> Tbl_Member_Insurance { get; set; }
    }
}
