//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Association.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_Member_Insurance
    {
        public int Inssur_ID { get; set; }
        public Nullable<int> Memb_ID { get; set; }
        public Nullable<System.DateTime> insur_Date { get; set; }
        public Nullable<int> insurance_Type_ID { get; set; }
        public Nullable<int> Insur_Value { get; set; }
    
        public virtual Tbl_Insurance_Type Tbl_Insurance_Type { get; set; }
        public virtual Tbl_Member_Registration Tbl_Member_Registration { get; set; }
    }
}
