//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Association.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_Subscribes
    {
        public int Sub_Year { get; set; }
        public int Mem_ID { get; set; }
        public Nullable<bool> Jan { get; set; }
        public Nullable<bool> Feb { get; set; }
        public Nullable<bool> Mar { get; set; }
        public Nullable<bool> Apr { get; set; }
        public Nullable<bool> May { get; set; }
        public Nullable<bool> June { get; set; }
        public Nullable<bool> July { get; set; }
        public Nullable<bool> August { get; set; }
        public Nullable<bool> Sep { get; set; }
        public Nullable<bool> Oct { get; set; }
        public Nullable<bool> Nov { get; set; }
        public Nullable<bool> Dec { get; set; }
        public Nullable<int> Sub_Paied { get; set; }
    
        public virtual Tbl_Member_Registration Tbl_Member_Registration { get; set; }
    }
}
