//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Association.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class View_3
    {
        public int Acc_TypeOfType_ID { get; set; }
        public string Acc_TypeOfType_Name { get; set; }
        public int Account_ID { get; set; }
        public string Account_Name { get; set; }
        public int Trans_Type_ID { get; set; }
        public string Trans_Type_Name { get; set; }
    }
}
