//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Association.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class View_1
    {
        public int Memb_ID { get; set; }
        public System.DateTime Memb_SysDate { get; set; }
        public Nullable<System.DateTime> Memb_Date { get; set; }
        public string Memb_EmpID { get; set; }
        public string Memb_Name { get; set; }
        public System.DateTime Memb_Birthdate { get; set; }
        public int Memb_Social_ID { get; set; }
        public Nullable<int> Memb_Children_Number { get; set; }
        public string Memb_Image { get; set; }
        public int Memb_Gender_ID { get; set; }
        public Nullable<int> Dept_ID { get; set; }
        public string Reason_Name { get; set; }
        public Nullable<System.DateTime> TransDate { get; set; }
        public string MembStatus_Name { get; set; }
        public int Reason_ID { get; set; }
        public int MembStatus_ID { get; set; }
        public int Social_ID { get; set; }
        public string Social_Name { get; set; }
    }
}
